---
- name: Deploy Nessus Agent
  hosts: "{{ hosts_list }}"
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Fail if OS unsupported
      fail:
        msg: "Unsupported OS {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
      when: ansible_facts['distribution'] not in ['RedHat', 'Ubuntu', 'Debian']

    - name: Remove existing Nessus token if force_relink
      shell: "/opt/nessus_agent/sbin/nessuscli agent unlink"
      ignore_errors: yes

    # ---------------- RHEL packages ----------------
    - name: Upload RHEL 7 package
      copy:
        src: "el7.rpm"
        dest: "/tmp/el7.rpm"
        mode: '0755'
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    - name: Install RHEL 7 package
      shell: "yum -y localinstall /tmp/el7.rpm"
      register: rhel7_install
      async: 0
      poll: 1
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    - name: Show RHEL 7 install logs
      debug:
        var: rhel7_install.stdout_lines
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"

    # Repeat similar tasks for RHEL 8/9
    - name: Upload RHEL 8 package
      copy:
        src: "el8.rpm"
        dest: "/tmp/el8.rpm"
        mode: '0755'
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

    - name: Install RHEL 8 package
      shell: "dnf -y localinstall /tmp/el8.rpm"
      register: rhel8_install
      async: 0
      poll: 1
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

    - name: Show RHEL 8 install logs
      debug:
        var: rhel8_install.stdout_lines
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "8"

    - name: Upload RHEL 9 package
      copy:
        src: "el9.rpm"
        dest: "/tmp/el9.rpm"
        mode: '0755'
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"

    - name: Install RHEL 9 package
      shell: "dnf -y localinstall /tmp/el9.rpm"
      register: rhel9_install
      async: 0
      poll: 1
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"

    - name: Show RHEL 9 install logs
      debug:
        var: rhel9_install.stdout_lines
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "9"

    # ---------------- Debian/Ubuntu ----------------
    - name: Upload Debian/Ubuntu package
      copy:
        src: "NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        dest: "/tmp/NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        mode: '0755'
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

    - name: Install Debian/Ubuntu package
      apt:
        deb: "/tmp/NessusAgent-10.9.0-ubuntu1604_amd64.deb"
        state: present
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']

    # ---------------- Optional Rapid7 removal ----------------
    - name: Upload Rapid7 removal script
      copy:
        src: "r7remover.sh"
        dest: "/tmp/r7remover.sh"
        mode: '0755'
      when: remove_rapid7 | default(false)

    - name: Run Rapid7 removal script
      shell: "bash /tmp/r7remover.sh"
      become: yes
      when: remove_rapid7 | default(false)

    # ---------------- Start & Link Nessus Agent ----------------
    - name: Enable and start Nessus Agent
      service:
        name: nessusagent
        state: started
        enabled: yes

    - name: Link Nessus Agent
      shell: >
        /opt/nessus_agent/sbin/nessuscli agent link
        --key={{ activation_key }}
        {% if mode == "cloud" %} --cloud {% else %} --manager-host={{ manager_host }} --manager-port={{ manager_port }} {% endif %}
      args:
        creates: "/opt/nessus_agent/.nessus/agent.key"
